# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = OOP/main.o OOP/User.o OOP/Book.o OOP/Booklist.o OOP/UserList.o
LINKOBJ  = OOP/main.o OOP/User.o OOP/Book.o OOP/Booklist.o OOP/UserList.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

OOP/main.o: OOP/main.cpp
	$(CPP) -c OOP/main.cpp -o OOP/main.o $(CXXFLAGS)

OOP/User.o: OOP/User.cpp
	$(CPP) -c OOP/User.cpp -o OOP/User.o $(CXXFLAGS)

OOP/Book.o: OOP/Book.cpp
	$(CPP) -c OOP/Book.cpp -o OOP/Book.o $(CXXFLAGS)

OOP/Booklist.o: OOP/Booklist.cpp
	$(CPP) -c OOP/Booklist.cpp -o OOP/Booklist.o $(CXXFLAGS)

OOP/UserList.o: OOP/UserList.cpp
	$(CPP) -c OOP/UserList.cpp -o OOP/UserList.o $(CXXFLAGS)
